# core/roadmap.py

DEFAULT_ROADMAP = [
    {
        "phase": 1,
        "period": "Days 1–30",
        "name": "Foundation Sprint",
        "goal": "Reframe your narrative. Package what already exists.",
        "tasks": [
            {"slug": "rewrite_star_stories",
             "text": "Rewrite your top 3 STAR stories in Why/What language (not How)",
             "tag": "New", "is_premium": False},
            {"slug": "package_governance_artifacts",
             "text": "Package 2–3 governance artifacts from existing work as one-page briefs",
             "tag": "Portfolio", "is_premium": False},
            {"slug": "write_ai_pov",
             "text": "Write your personal AI point of view (1 page)",
             "tag": "New", "is_premium": False},
            {"slug": "identify_ownership_gap",
             "text": "Identify the one AI gap nobody owns in your current organization",
             "tag": "Signal", "is_premium": False},
        ]
    },
    {
        "phase": 2,
        "period": "Days 31–60",
        "name": "Visibility Build",
        "goal": "Create external signal. Start the conversation.",
        "tasks": [
            {"slug": "publish_linkedin_article",
             "text": "Publish your first LinkedIn article on AI in your specific domain",
             "tag": "Public", "is_premium": False},
            {"slug": "director_conversations",
             "text": "Have 3 conversations with current Directors or VPs in AI roles",
             "tag": "Network", "is_premium": False},
            {"slug": "apply_first_roles",
             "text": "Apply to 3–5 Director-level roles — treat as learning data",
             "tag": "Apply", "is_premium": False},
            {"slug": "regulatory_framework",
             "text": "Read one regulatory framework: NIST AI RMF or EU AI Act summary",
             "tag": "Governance", "is_premium": False},
        ]
    },
    {
        "phase": 3,
        "period": "Months 3–6",
        "name": "Evidence Accumulation",
        "goal": "Build the portfolio. Create the interview-ready narrative.",
        "tasks": [
            {"slug": "first_director_interview",
             "text": "Complete first Director-level interview — debrief regardless of outcome",
             "tag": "Interview", "is_premium": False},
            {"slug": "cross_functional_initiative",
             "text": "Own one cross-functional AI initiative in current role",
             "tag": "Leadership", "is_premium": False},
            {"slug": "monthly_articles",
             "text": "Publish one AI leadership article per month",
             "tag": "Thought Lead", "is_premium": False},
            {"slug": "product_case_study",
             "text": "Document your AI product/project as a formal case study",
             "tag": "Portfolio", "is_premium": True},
        ]
    },
    {
        "phase": 4,
        "period": "Months 7–12",
        "name": "The Title Pursuit",
        "goal": "Close the role. Negotiate the level.",
        "tasks": [
            {"slug": "four_permanent_answers",
             "text": "Refine your four permanent Director answers with story evidence",
             "tag": "Interview", "is_premium": False},
            {"slug": "director_network",
             "text": "Build a network of 10+ people at Director/VP AI level",
             "tag": "Network", "is_premium": False},
            {"slug": "apply_ten_roles",
             "text": "Apply to 10+ roles — filter for IC-to-Director pathways",
             "tag": "Apply", "is_premium": False},
            {"slug": "board_communication",
             "text": "Practice board-level AI communication: consequence → mechanism → recommendation",
             "tag": "New Skill", "is_premium": True},
        ]
    },
    {
        "phase": 5,
        "period": "Months 12–18",
        "name": "Director → VP Signal",
        "goal": "Once in the Director role: build toward VP trajectory.",
        "tasks": [
            {"slug": "governance_framework_90days",
             "text": "Establish AI governance framework in first 90 days in role",
             "tag": "VP Prep", "is_premium": True},
            {"slug": "leadership_bench",
             "text": "Identify and develop the next Senior Manager on your team",
             "tag": "People", "is_premium": True},
            {"slug": "three_year_vision",
             "text": "Define a 3-year AI vision for your function — present to C-suite",
             "tag": "Vision", "is_premium": True},
            {"slug": "external_thought_leadership",
             "text": "Establish external AI thought leadership: speaking, writing, advising",
             "tag": "Market", "is_premium": True},
        ]
    }
]

DEFAULT_FEARS = [
    {"slug": "moving_target",
     "title": "The Moving Target",
     "summary": "By the time I'm ready, the requirements will change again.",
     "reframe": "You are not preparing to know AI. You are preparing to lead through it. Pattern recognition is more valuable than any specific skill list."},
    {"slug": "imposter_syndrome",
     "title": "Imposter Syndrome",
     "summary": "In the interview or first board meeting, they'll realize I'm not the real thing.",
     "reframe": "Impostors use vague language. You have chapter and verse — specific, verified, quantified stories. Specificity is credibility."},
    {"slug": "age_relevance",
     "title": "Age & Relevance",
     "summary": "Am I too old or too early for this transition?",
     "reframe": "Your unfair advantage is scar tissue. You have seen what happens when organizations fall in love with a technology before building the governance for it."},
    {"slug": "how_identity",
     "title": "The How Identity Crisis",
     "summary": "If I stop being the technical expert, who am I?",
     "reframe": "The Director does not need to be the most technical person in the room. They need to ask the right questions of technical people. That is a more valuable skill."},
    {"slug": "no_reports",
     "title": "No Direct Reports",
     "summary": "Every Director JD asks for people management. I don't have formal reports.",
     "reframe": "Target Director of AI Strategy or Director of AI Programs first. These are IC-to-director pathways. Once you have the title, people follow the role."},
    {"slug": "governance_overwhelm",
     "title": "Governance Overwhelm",
     "summary": "I can't learn law and regulation on top of everything else.",
     "reframe": "You need to know enough to ask the right questions of lawyers. Read NIST AI RMF. One page on EU AI Act high-risk systems. That is enough to lead."},
    {"slug": "comparison_trap",
     "title": "The Comparison Trap",
     "summary": "Others on LinkedIn are so much further ahead.",
     "reframe": "LinkedIn shows finished products, not work in progress. The people posting VP titles right now often built that role from scratch with less experience than you have."},
]
